name: CI Runners

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
    pull_request:
        branches:
            - main
        paths:
            - "src/**"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Environments
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set up project
              run: npm ci

            - name: Build project
              run: npm run build --if-present

            - name: Run tests
              run: npm test
